name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    strategy:
      # Don't crash if the other workers fail (i.e. 27+1.17 currently)
      fail-fast: false
      matrix:
        otp: ['25', '26', '27']
        elixir: ['1.15', '1.16', '1.17']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}} # Define the OTP version [required]
        elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: otp-${{matrix.otp}}-ex-${{matrix.elixir}}-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: otp-${{matrix.otp}}-ex-${{matrix.elixir}}-${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
